import { getSetupQuestStepTitle } from "../content/setup-quests";
import type { ProjectDefinition } from "../content/types";

function Check({ done, children }: { done: boolean; children: React.ReactNode }) {
  return <div className={done ? "done" : ""}><i>{done ? "✓" : "○"}</i><span>{children}</span></div>;
}

function CodexSetup({ step }: { step: number }) {
  const stage = step <= 5 ? "download" : step <= 8 ? "login" : step <= 13 ? "workspace" : "ready";
  return <div className="setup-ui codex-setup-ui"><aside><b>ChatGPT</b><span className={stage === "download" ? "active" : ""}>↓ Установка</span><span className={stage === "login" ? "active" : ""}>◉ Codex</span><span className={stage === "workspace" ? "active" : ""}>▱ Проекты Codex</span><span className={stage === "ready" ? "active" : ""}>✓ Готово</span><footer>Mac · Windows</footer></aside><main><header><div><small>ПОДГОТОВКА К РАБОТЕ</small><h3>{stage === "download" ? "Официальное приложение" : stage === "login" ? "Codex выбран" : stage === "workspace" ? "Учебная папка подключена" : "Codex работает"}</h3></div><b>{String(step).padStart(2,"0")}/17</b></header><section>{stage === "download" && <div className="setup-download"><span>⌘</span><b>chatgpt.com/download</b><small>macOS или Windows определится автоматически</small><button>Скачать приложение</button></div>}{stage === "login" && <div className="setup-menu"><span>ChatGPT⌄</span><b>Chat</b><b>Work</b><b className="selected">Codex ✓</b></div>}{stage === "workspace" && <div className="setup-workspace"><small>РАБОЧАЯ ПАПКА</small><b>Документы / Проекты Codex / codex-test</b><div className="setup-prompt">Создай страницу «Codex работает»… <button>↑</button></div></div>}{stage === "ready" && <div className="setup-checks"><Check done>Приложение установлено</Check><Check done>Codex выбран</Check><Check done>Папка подключена</Check><Check done={step >= 17}>Тестовая страница работает</Check></div>}</section><footer>Пароль и личные документы не передаются</footer></main></div>;
}

function ServerSetup({ step }: { step: number }) {
  const stage = step === 1 ? "law" : step === 2 ? "plan" : step === 3 ? "cart" : step === 4 ? "checkout" : step === 5 ? "cabinet" : step === 6 ? "ssh" : step === 7 ? "protect" : step === 8 ? "use" : "legal";
  const stageIndex = step === 1 ? 0 : step <= 4 ? 1 : step === 5 ? 2 : step <= 7 ? 3 : step === 8 ? 4 : 5;
  const title = stage === "law" ? "Нужен ли сервер" : stage === "plan" ? "Россия · подходящий VPS" : stage === "cart" ? "Скидка 60% применена" : stage === "checkout" ? "Оформление владельца" : stage === "cabinet" ? "Сервер Active" : stage === "ssh" ? "Публичный SSH-ключ" : stage === "protect" ? "Защита и бэкапы" : stage === "use" ? "Три понятных режима" : "Факты для специалиста";
  return <div className="setup-ui server-setup-ui"><header><div><small>ADMINVPS · РОССИЙСКИЙ VPS</small><h3>{title}</h3></div><span>{stage === "cabinet" ? "ACTIVE" : stage === "cart" ? "−60%" : "ПРОВЕРКА"}</span></header><nav>{["Нужно","Покупка","Кабинет","Защита","Работа","152-ФЗ"].map((item,index)=><b key={item} className={index <= stageIndex ? "done" : ""}>{index+1}<small>{item}</small></b>)}</nav><main>{stage === "plan" ? <><section><small>ЛОКАЦИЯ</small><b>Россия</b><span>первичная база в РФ</span></section><section><small>ТАРИФ</small><b>Минимальный подходящий</b><span>цена проверена на сайте</span></section><section><small>СИСТЕМА</small><b>Ubuntu LTS</b><span>сверьте перед оплатой</span></section></> : stage === "cart" ? <><section><small>КОД СКИДКИ</small><b>SUBMARINE123</b><span>применён ✓</span></section><section><small>СКИДКА</small><b>60%</b><span>первый месяц</span></section><section><small>УСЛОВИЯ</small><b>1 сервер</b><span>кроме Lite</span></section></> : stage === "checkout" ? <><section><small>ВЛАДЕЛЕЦ</small><b>Имя · Фамилия</b><span>Email · Телефон</span></section><section><small>ОПЛАТА</small><b>Российская карта</b><span>сумма проверена</span></section><section><small>СЕКРЕТЫ</small><b>Не показываем</b><span>пароль · CVC · SMS</span></section></> : stage === "cabinet" ? <><section><small>УСЛУГИ</small><b>Товары/Услуги</b><span>сервер открыт</span></section><section><small>СТАТУС</small><b>Active</b><span>следующая оплата записана</span></section><section><small>АДРЕС</small><b>185.•••.•••.42</b><span>публичный IP сохранён</span></section></> : stage === "ssh" ? <><section><small>РАЗДЕЛ</small><b>SSH Keys</b><span>Добавить</span></section><section><small>ДОБАВЛЯЕМ</small><b>ssh-ed25519…</b><span>только публичный ключ</span></section><section><small>НЕ ПОКАЗЫВАЕМ</small><b>Private key</b><span>остаётся на компьютере</span></section></> : <div className="setup-checks"><Check done={step >= 1}>Необходимость сервера понятна</Check><Check done={step >= 3}>Россия и промокод проверены</Check><Check done={step >= 5}>IP и следующая оплата сохранены</Check><Check done={step >= 7}>SSH, firewall и бэкапы настроены</Check><Check done={step >= 8}>Команда для обычной работы сохранена</Check><Check done={step >= 9}>Факты и вопросы специалисту собраны</Check></div>}</main><footer><b>Важно:</b> покупка российского VPS — инфраструктурная часть, а не готовое соответствие 152-ФЗ</footer></div>;
}

function ApiSetup({ step }: { step: number }) {
  const providers = [
    ["Polza.ai","агрегатор · РФ"],
    ["OpenRouter","агрегатор · международный"],
    ["Qwen","модели Alibaba"],
    ["OpenAI","прямой провайдер"],
  ];
  const stage = step <= 4 ? "choose" : step === 5 ? "provider" : step <= 10 ? "secret" : "test";
  return <div className="setup-ui api-setup-ui"><header><div><small>БЕЗОПАСНОЕ API-ПОДКЛЮЧЕНИЕ</small><h3>{stage === "choose" ? "Проект → API → модель" : stage === "provider" ? "Выберите одного провайдера" : stage === "secret" ? "Секрет хранится на сервере" : "Тест и контроль расходов"}</h3></div><span>КЛЮЧ СКРЫТ</span></header>{stage === "provider" || stage === "choose" ? <main className="provider-grid">{providers.map(([name,type])=><section key={name} className={stage === "provider" ? "selected" : ""}><i>{name === "Polza.ai" ? "P" : name === "OpenRouter" ? "O" : name === "Qwen" ? "Q" : "AI"}</i><b>{name}</b><small>{type}</small></section>)}</main> : stage === "secret" ? <main className="secret-flow"><section><small>СЕРВЕРНАЯ ПЕРЕМЕННАЯ</small><b>{step === 8 ? "OPENROUTER_API_KEY" : "PROVIDER_API_KEY"}</b><span>sk-••••••••••••</span></section><b>→</b><section><small>БРАУЗЕР</small><b>Секрета нет</b><span>только безопасный ответ</span></section></main> : <main className="setup-checks"><Check done>Один короткий запрос</Check><Check done={step >= 12}>Код ошибки понятен</Check><Check done={step >= 13}>Кнопка отзыва найдена</Check><Check done={step >= 14}>Лимит расходов установлен</Check></main>}<footer>Никогда не вставляйте настоящий ключ в Академию, чат, скриншот или публичный код</footer></div>;
}

export function SetupQuestPrototypeScene({ project, step, mobile = false }: { project: ProjectDefinition; step: number; mobile?: boolean }) {
  const title = getSetupQuestStepTitle(project.slug, step) ?? project.title;
  return <div className={`setup-prototype ${mobile ? "mobile" : ""}`} data-setup-prototype={project.slug}><div className="setup-prototype-title"><small>УРОВЕНЬ {String(step).padStart(2,"0")}</small><b>{title}</b></div>{project.slug === "install-codex" ? <CodexSetup step={step}/> : project.slug === "server-152fz" ? <ServerSetup step={step}/> : <ApiSetup step={step}/>}</div>;
}
